export const COUNTRIES = {
  CL: { name: 'Chile',           flag: '🇨🇱', locale: 'es-CL', currency: 'CLP', timezone: 'America/Santiago',              language: 'es',    idField: 'RUT',          accountTypes: ['Cuenta corriente', 'Cuenta vista', 'Cuenta de ahorro', 'Cuenta RUT'],
    banks: ['Banco Estado', 'Banco de Chile', 'Santander', 'BCI', 'Itaú', 'Scotiabank', 'Security', 'Consorcio', 'Falabella', 'Ripley', 'BICE', 'Coopeuch', 'Tenpo', 'Mach', 'Mercado Pago', 'Otro'] },
  AR: { name: 'Argentina',       flag: '🇦🇷', locale: 'es-AR', currency: 'ARS', timezone: 'America/Argentina/Buenos_Aires', language: 'es',    idField: 'CUIL / CUIT',  accountTypes: ['Cuenta corriente', 'Caja de ahorro'],
    banks: ['Banco Nación', 'Banco Provincia', 'Santander', 'BBVA', 'Galicia', 'HSBC', 'Itaú', 'Macro', 'Bancor', 'Naranja X', 'Mercado Pago', 'Ualá', 'Brubank', 'Otro'] },
  MX: { name: 'México',          flag: '🇲🇽', locale: 'es-MX', currency: 'MXN', timezone: 'America/Mexico_City',           language: 'es',    idField: 'RFC / CURP',   accountTypes: ['Cuenta de débito', 'Cuenta de ahorro', 'Cuenta corriente'],
    banks: ['BBVA', 'Citibanamex', 'Santander', 'Banorte', 'HSBC', 'Inbursa', 'Scotiabank', 'Baz', 'Nu (Nubank)', 'Hey Banco', 'Mercado Pago', 'Spin by OXXO', 'Otro'] },
  CO: { name: 'Colombia',        flag: '🇨🇴', locale: 'es-CO', currency: 'COP', timezone: 'America/Bogota',                language: 'es',    idField: 'Cédula / NIT', accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['Bancolombia', 'Davivienda', 'Banco de Bogotá', 'BBVA', 'Scotiabank Colpatria', 'Itaú', 'Banco Popular', 'AV Villas', 'Nequi', 'Daviplata', 'Mercado Pago', 'Otro'] },
  PE: { name: 'Perú',            flag: '🇵🇪', locale: 'es-PE', currency: 'PEN', timezone: 'America/Lima',                  language: 'es',    idField: 'DNI / RUC',    accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['BCP', 'BBVA', 'Interbank', 'Scotiabank', 'BanBif', 'Pichincha', 'Mibanco', 'Yape', 'Plin', 'Mercado Pago', 'Otro'] },
  BR: { name: 'Brasil',          flag: '🇧🇷', locale: 'pt-BR', currency: 'BRL', timezone: 'America/Sao_Paulo',             language: 'pt-BR', idField: 'CPF / CNPJ',   accountTypes: ['Conta corrente', 'Conta poupança', 'Conta salário'],
    banks: ['Nubank', 'Itaú', 'Bradesco', 'Banco do Brasil', 'Caixa Econômica', 'Santander', 'Inter', 'C6 Bank', 'PicPay', 'Mercado Pago', 'Outro'] },
  UY: { name: 'Uruguay',         flag: '🇺🇾', locale: 'es-UY', currency: 'UYU', timezone: 'America/Montevideo',            language: 'es',    idField: 'Cédula / RUT', accountTypes: ['Cuenta corriente', 'Caja de ahorro'],
    banks: ['BROU', 'Santander', 'BBVA', 'Itaú', 'Scotiabank', 'HSBC', 'OCA', 'Prex', 'Otro'] },
  PY: { name: 'Paraguay',        flag: '🇵🇾', locale: 'es-PY', currency: 'PYG', timezone: 'America/Asuncion',              language: 'es',    idField: 'RUC / CI',     accountTypes: ['Cuenta corriente', 'Cuenta de ahorro'],
    banks: ['Banco Nacional', 'Itaú', 'Continental', 'Familiar', 'BBVA', 'GNB', 'Mercado Pago', 'Otro'] },
  BO: { name: 'Bolivia',         flag: '🇧🇴', locale: 'es-BO', currency: 'BOB', timezone: 'America/La_Paz',                language: 'es',    idField: 'NIT / CI',     accountTypes: ['Cuenta corriente', 'Caja de ahorros'],
    banks: ['Banco Unión', 'BNB', 'Banco Mercantil Santa Cruz', 'BISA', 'FIE', 'Banco Económico', 'Otro'] },
  EC: { name: 'Ecuador',         flag: '🇪🇨', locale: 'es-EC', currency: 'USD', timezone: 'America/Guayaquil',             language: 'es',    idField: 'RUC / CI',     accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['Banco Pichincha', 'Banco Guayaquil', 'Produbanco', 'Banco del Pacífico', 'Banco Internacional', 'Banco Bolivariano', 'Otro'] },
  VE: { name: 'Venezuela',       flag: '🇻🇪', locale: 'es-VE', currency: 'VES', timezone: 'America/Caracas',               language: 'es',    idField: 'RIF / CI',     accountTypes: ['Cuenta corriente', 'Cuenta de ahorro'],
    banks: ['Banesco', 'Mercantil', 'BBVA Provincial', 'Banco de Venezuela', 'Banco del Tesoro', 'BNC', 'Otro'] },
  GT: { name: 'Guatemala',       flag: '🇬🇹', locale: 'es-GT', currency: 'GTQ', timezone: 'America/Guatemala',             language: 'es',    idField: 'NIT / DPI',    accountTypes: ['Cuenta monetaria', 'Cuenta de ahorro'],
    banks: ['Banrural', 'Industrial', 'G&T Continental', 'Banistmo', 'BAC', 'Banco Agromercantil', 'Otro'] },
  CR: { name: 'Costa Rica',      flag: '🇨🇷', locale: 'es-CR', currency: 'CRC', timezone: 'America/Costa_Rica',            language: 'es',    idField: 'Cédula / NIT', accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['BCR', 'BNCR', 'BAC', 'Scotiabank', 'Davivienda', 'Promerica', 'Otro'] },
  PA: { name: 'Panamá',          flag: '🇵🇦', locale: 'es-PA', currency: 'PAB', timezone: 'America/Panama',                language: 'es',    idField: 'Cédula / RUC', accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['Banistmo', 'BAC', 'Banco General', 'Global Bank', 'Scotiabank', 'Caja de Ahorros', 'Otro'] },
  DO: { name: 'Rep. Dominicana', flag: '🇩🇴', locale: 'es-DO', currency: 'DOP', timezone: 'America/Santo_Domingo',         language: 'es',    idField: 'Cédula / RNC', accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['Banco Popular', 'BHD León', 'Scotiabank', 'Banreservas', 'Banco Santa Cruz', 'Otro'] },
  SV: { name: 'El Salvador',     flag: '🇸🇻', locale: 'es-SV', currency: 'USD', timezone: 'America/El_Salvador',           language: 'es',    idField: 'DUI / NIT',    accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['Banco Agrícola', 'Banco Cuscatlán', 'Davivienda', 'BAC', 'Promerica', 'Otro'] },
  HN: { name: 'Honduras',        flag: '🇭🇳', locale: 'es-HN', currency: 'HNL', timezone: 'America/Tegucigalpa',           language: 'es',    idField: 'RTN / DNI',    accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['Banco Atlántida', 'BAC', 'Ficohsa', 'Banpaís', 'Davivienda', 'Otro'] },
  NI: { name: 'Nicaragua',       flag: '🇳🇮', locale: 'es-NI', currency: 'NIO', timezone: 'America/Managua',               language: 'es',    idField: 'RUC / Cédula', accountTypes: ['Cuenta corriente', 'Cuenta de ahorros'],
    banks: ['Banpro', 'BAC', 'Lafise Bancentro', 'Ficohsa', 'Avanz', 'Otro'] },
  CU: { name: 'Cuba',            flag: '🇨🇺', locale: 'es-CU', currency: 'CUP', timezone: 'America/Havana',                language: 'es',    idField: 'CI',           accountTypes: ['Cuenta corriente', 'Cuenta de ahorro'],
    banks: ['Banco Metropolitano', 'BPA', 'Bandec', 'BFI', 'Otro'] },
}

export const DEFAULT_COUNTRY = 'CL'
